/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author joseacosta
 */
public class Buscar extends javax.swing.JDialog {

    private GestorInventario gestor;
    private  ModeloTablaInventario modelo;
    private JTable tabla;
   

    /**
     * JDialog modal. 
     * Esto bloquea la ventana principal hasta que esta se cierre.
     * Le pasamos el gestor de inventario para poder usar sus 
     * métodos de búsqueda.
     */
    public Buscar(java.awt.Frame parent, boolean modal, GestorInventario gestor, ModeloTablaInventario modelo, JTable tabla) {
        super(parent, modal);
        this.gestor = gestor;
        this.modelo= modelo;
        this.tabla = tabla;
        initComponents();
        this.setLocationRelativeTo(parent); // Centrar relativo a la ventana padre (Main)
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barraBusqueda = new javax.swing.JTextPane();
        botonConfirmarBusqueda = new javax.swing.JButton();

        setTitle("Buscar Producto");

        jScrollPane1.setViewportView(barraBusqueda);

        botonConfirmarBusqueda.setText("Buscar");
        botonConfirmarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConfirmarBusqueda)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonConfirmarBusqueda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarBusquedaActionPerformed
        String nombre = barraBusqueda.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre para buscar.", "Entrada Vacía", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int indiceProductoEncontrado = modelo.encuentraIndiceFilaPorNombre(nombre) ;
       

        if (indiceProductoEncontrado >= 0) {
            // Seleccionamos la fila
            tabla.setRowSelectionInterval(indiceProductoEncontrado, indiceProductoEncontrado);
            // Aseguramos de que la fila seleccionada sea visible
            // Hacemos scroll hasta la fila
            tabla.scrollRectToVisible(tabla.getCellRect(indiceProductoEncontrado, 0, true));
            JOptionPane.showMessageDialog(null, "Producto " + nombre + " encontrado y seleccionado.");
            this.dispose();

        } else {
        // Si no se encuentra, informamos al usuario
            JOptionPane.showMessageDialog(null, "Producto no encontrado: " + nombre);    
        }
    }//GEN-LAST:event_botonConfirmarBusquedaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane barraBusqueda;
    private javax.swing.JButton botonConfirmarBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
