/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.AbstractAction;


/**
 *
 * @author joseacosta
 */
public class JFrame extends javax.swing.JFrame {
    private GestorInventario gestor; // Declaramos la clase de gestor
    private ModeloTablaInventario modeloTabla; // Declaramos la clase de la tabla

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        gestor = new GestorInventario("inventario.txt");
        initComponents();
    }

      /**
     * Configura el JTable, le asigna el modelo y los editores de botones.
     */
    private void configurarTabla() {
        modeloTabla = new ModeloTablaInventario(gestor.getInventario());
        tablaInventario.setModel(modeloTabla);

        // Acción para el botón de editar
        Action editarAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                int modelRow = Integer.parseInt(e.getActionCommand());
                editarProducto(modelRow);
            }
        };

        // Acción para el botón de eliminar
        Action eliminarAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                int modelRow = Integer.parseInt(e.getActionCommand());
                eliminarProducto(modelRow);
            }
        };

        // Asignamos el renderizador/editor a las columnas de botones
        new ButtonColumn(panel, editarAction, 4); // Columna 4 para Editar
        new ButtonColumn(panel, eliminarAction, 5); // Columna 5 para Eliminar
        
        // Opcional: ajustar el ancho de las columnas de botones
        panel.getColumnModel().getColumn(4).setPreferredWidth(50);
        panel.getColumnModel().getColumn(5).setPreferredWidth(60);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        barraSuperior = new javax.swing.JMenuBar();
        botonArchivo = new javax.swing.JMenu();
        botonSalir = new javax.swing.JMenuItem();
        botonOperaciones = new javax.swing.JMenu();
        botonAgregar = new javax.swing.JMenuItem();
        botonModificar = new javax.swing.JMenuItem();
        botonEliminar = new javax.swing.JMenuItem();
        botonBuscar = new javax.swing.JMenuItem();
        botonListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panel.setViewportView(tablaInventario);

        botonArchivo.setText("Archivo");

        botonSalir.setText("Salir");
        botonArchivo.add(botonSalir);

        barraSuperior.add(botonArchivo);

        botonOperaciones.setText("Operaciones");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        botonOperaciones.add(botonAgregar);

        botonModificar.setText("Modificar");
        botonOperaciones.add(botonModificar);

        botonEliminar.setText("Eliminar");
        botonOperaciones.add(botonEliminar);

        botonBuscar.setText("Buscar Por Nombre");
        botonOperaciones.add(botonBuscar);

        botonListar.setText("Listar por Categoría");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });
        botonOperaciones.add(botonListar);

        barraSuperior.add(botonOperaciones);

        setJMenuBar(barraSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraSuperior;
    private javax.swing.JMenuItem botonAgregar;
    private javax.swing.JMenu botonArchivo;
    private javax.swing.JMenuItem botonBuscar;
    private javax.swing.JMenuItem botonEliminar;
    private javax.swing.JMenuItem botonListar;
    private javax.swing.JMenuItem botonModificar;
    private javax.swing.JMenu botonOperaciones;
    private javax.swing.JMenuItem botonSalir;
    private javax.swing.JScrollPane panel;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables
}
