/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author joseacosta y victor
 */
public class Listar extends javax.swing.JDialog {

    private GestorInventario gestor;
    private TableRowSorter<ModeloTablaInventario> filtroTabla;
    private JButton botonEliminarFiltro;
    

    public Listar(java.awt.Frame parent, boolean modal, GestorInventario gestor, TableRowSorter<ModeloTablaInventario> filtroTabla, JButton botonEliminarFiltro) {
        super(parent, modal);
        this.gestor = gestor;
        this.filtroTabla = filtroTabla;
        this.botonEliminarFiltro = botonEliminarFiltro;
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    
    private void ejecutarFiltro(){
        String textoFiltro = barraFiltrar.getText();
        // ' Ejemplo ' => 'Ejemplo'
        if(textoFiltro.trim().length() == 0){
            // Si texto viene vacio seteamos filtro a null
            filtroTabla.setRowFilter(null);
            JOptionPane.showMessageDialog(null, "Agrega un filtro valido.");
            
            
            botonEliminarFiltro.setVisible(false);
      
            
        }else {
            // (?i) hace que la búsqueda no distinga entre mayúsculas y minúsculas
            filtroTabla.setRowFilter(RowFilter.regexFilter("(?i)" + textoFiltro));
            JOptionPane.showMessageDialog(null, "Se ha filtrado los resultados.");
            this.dispose();
            botonEliminarFiltro.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barraFiltrar = new javax.swing.JTextPane();
        botonFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Productos por Categoría");

        jScrollPane1.setViewportView(barraFiltrar);

        botonFiltrar.setText("Filtrar");
        botonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonFiltrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFiltrar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarActionPerformed
        ejecutarFiltro();
    }//GEN-LAST:event_botonFiltrarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane barraFiltrar;
    private javax.swing.JButton botonFiltrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
